### ISSUE TITLE
Release 1.3.1-gcm.0 

### ISSUE THREAD

**Issue by maelvls** [jetstack/jetstack-secure-gcm#47]
We released cert-manager 1.3.1 last week and we want to let new users of GCM be able to use v1.3.1 when deployment both using the CLI installation and the click-to-deploy installation.

| ⚠️ Note that we DO NOT HAVE an upgrade process documented yet. This has not been prioritized yet, see #48. If a user has installed `1.1.0-gcm.7` (either using the CLI installation or the click-to-deploy installation), then they do not have a way to upgrade to 1.3.1-gcm.0 yet. |
|-|

Progress for releasing `1.3.1-gcm.0`:

- [x] https://github.com/jakexks/go-providence-checker/issues/2: fix `go-providence-checker` so that it works for preflight
- [x] find out about the flackiness, cf [convo](https://jetstack.slack.com/archives/C63VC8FAT/p1619453903448100)
- [x] open an issue about `logex` not having a LICENSE file → https://github.com/jetstack/preflight/issues/229
- [x] #10: Add LICENSES.txt to cert-manager, jetstack-secure-agent and google-cas-issuer images using `go-providence-checker` -> done in https://github.com/jetstack/jetstack-secure-gcm/pull/49
- [x] add the new RBAC rules for the Approval API to the google-cas-issuer chart
- [x] Follow the [manual GCM update instructions](https://github.com/jetstack/jetstack-secure-gcm/blob/main/docs/TESTING-DEPLOYER.md#cutting-a-new-release) to create a GitHub Release
- [ ] Update README.md to point to `1.3.1-gcm.0`.

**Comment by maelvls** [comment]
@james-w When do we want to have that done? I am currently focusing on https://github.com/cert-manager/website/issues/426, but I could prioritize the upgrade of GCM to 1.3.

**Comment by maelvls** [comment]
After this morning's cert-manager internal meeting, upgrading to v1.3.1 has been prioritized for this week.

**Comment by maelvls** [comment]
Oops, [looks like](https://console.cloud.google.com/cloud-build/builds/da511232-b6e8-4708-a98e-2c24b7341f1c?project=jetstack-public&authuser=3) the cluster had been scaled to 0. I'll add an instruction to scale to 1 and then scale to 0 afterward:

> Step #13 - "verify": 10s         Warning   FailedScheduling       pod/preflight-f7484c6f5-pgtpv      0/1 nodes are available: 1 Insufficient cpu.

**Comment by maelvls** [comment]
I am stuck on another [issue](https://console.cloud.google.com/cloud-build/builds;region=global/15dd6e19-a951-4ed6-889d-a8bd00c8434d;step=12?authuser=3&project=jetstack-public).

```
I0429 16:17:06.312677       1 main.go:123]  >   0: kubectl smoke test: PASSED
I0429 16:17:06.313019       1 main.go:123]  >   1: Create test issuer and self signed cert: PASSED
E0429 16:17:06.313355       1 main.go:125]  >   2: Try to get new cert: FAILED
E0429 16:17:06.313422       1 main.go:125]  >   3: Try to get cert secret: FAILED
I0429 16:17:06.313448       1 main.go:123]  >   4: Delete issuer and self signed cert: PASSED
```

Looking at [the test suite](https://github.com/jetstack/jetstack-secure-gcm/blob/efca03b3fd9b7402dad29e9e202f171512d5bcf1/smoke-test.yaml#L40-L53), the certificate does not become ready within 2 minutes... Not sure why, and this is blocking the release of GCM 1.3.1! 😩

I have seen the following event though:

```
6s          Warning   CRNotApproved          certificaterequest/googlecas-cert-2z78m   certificate request is not approved yet
```

I have very little "insights" except for [these cloud build logs](https://console.cloud.google.com/cloud-build/builds;region=global/15dd6e19-a951-4ed6-889d-a8bd00c8434d;step=12?authuser=3&project=jetstack-public) :disappointed:   

cc @jakexks

**Comment by jakexks** [comment]
I'll take a look

**Comment by maelvls** [comment]
You are right, I forgot to add the new RBAC rules :sweat_smile:

**Comment by maelvls** [comment]
Done! I [just submitted](https://groups.google.com/a/jetstack.io/g/cert-manager-maintainers/c/QF2naUYWmUc/m/VY5hLUN9AQAJ) 1.3.1-gcm.0! Let's hope it gets reviewed during the night.

**Comment by maelvls** [comment]
The 1.3.1-gcm.0 is now [live](https://groups.google.com/a/jetstack.io/g/cert-manager-maintainers/c/QF2naUYWmUc/m/HSL13e2-AQAJ)!
